[package]
name = "m3u_spotify"
version = "0.1.0"
authors = ["Mark Ellis <m@rkellis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "0.3"
rspotify = "0.7"
